const assert = require('assert');
const { formatArl, getFoldingRanges } = require('../src/arl-structure.cjs');
const messy=['func void main()','if(a>0)','MoveJ(p1)','elseif(a==0)','if(b)','MoveL(p2)','endif','else','while(x) doSomething()','print "x"','endif','endfunc'].join('\n');
const expected=['func void main()','    if(a>0)','        MoveJ(p1)','    elseif(a==0)','        if(b)','            MoveL(p2)','        endif','    else','        while(x) doSomething()','        print "x"','    endif','endfunc'].join('\n');
assert.strictEqual(formatArl(messy),expected);
const switchMessy=['switch(mode)','case 1:','MoveJ(p1)','case 2:','MoveL(p2)','default:','MoveJ(p3)','endswitch'].join('\n');
const switchExpected=['switch(mode)','case 1:','    MoveJ(p1)','case 2:','    MoveL(p2)','default:','    MoveJ(p3)','endswitch'].join('\n');
assert.strictEqual(formatArl(switchMessy),switchExpected);
const compact=['if(a) MoveJ(p1)','print "same level"'].join('\n'); assert.strictEqual(formatArl(compact),compact);
const foldText=['func void main()','    if(a)','        while(b)','            MoveJ(p1)','        endwhile','    else','        MoveL(p2)','    endif','endfunc'].join('\n');
assert.deepStrictEqual(getFoldingRanges(foldText),[{start:0,end:7,type:'func'},{start:1,end:6,type:'if'},{start:2,end:3,type:'while'}]);
console.log('ARL formatter/folding tests passed');
