const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const pkg=read('package.json');
const cfg=read('language-configuration.json');
const grammar=read('syntaxes/arl.tmLanguage.json');
assert.strictEqual(pkg.version,'1.0.0');
assert.strictEqual(pkg.publisher,'David-Workshop');
assert.strictEqual(pkg.displayName,'%extension.displayName%');
assert.strictEqual(pkg.contributes.configurationDefaults['[arl]']['editor.defaultFormatter'],'David-Workshop.peitian-arl-language-support');
assert.deepStrictEqual(cfg.comments.blockComment,['/*','*/']);
assert(grammar.repository.comments.patterns.some(p=>p.name==='comment.block.arl'&&p.begin==='/\\*'&&p.end==='\\*/'));
for(const file of ['package.nls.json','package.nls.zh-cn.json','README.md','README.zh-CN.md','LICENSE','icon.png']) assert(fs.existsSync(path.join(root,file)),`Missing ${file}`);
assert(pkg.repository.url.includes('YoyoDavidGo/Peitian-Robot-ARL-Language-Support'));
assert(pkg.bugs.url.endsWith('/issues'));
assert.strictEqual(pkg.license,'SEE LICENSE IN LICENSE');
console.log('ARL extension Marketplace validation passed');
